server:
  port: 8082
  undertow:
    io-threads: 2
    worker-threads: 32
    buffer-size: 1024
    directBuffers: true

spring:
  datasource:
    #schema: classpath*:scripts/schema.sql
    #continue-on-error: false
    #sql-script-encoding: utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://122.112.150.62:3306/db_mblog?useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 196801135
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate.format_sql: true
      hibernate.naming.physical-strategy: org.hibernate.scripts.model.naming.PhysicalNamingStrategyStandardImpl
      hibernate.cache.use_second_level_cache: false
      hibernate.search.default.directory_provider: filesystem
      hibernate.search.default.indexBase: ${site.location}/storage/indexes
  devtools:
    enabled: true
  cache:
    type: ehcache
    ehcache:
      config: classpath:ehcache.xml
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  freemarker:
    template-loader-path:
      - classpath:/templates
      - file:${site.location}/storage/templates
    cache: false
    check-template-location: true
    request-context-attribute: request
    charset: utf-8
    suffix: .ftl
    settings:
      classic_compatible: true
      template_exception_handler: rethrow
      template_update_delay: 0
      datetime_format: yyyy-MM-dd HH:mm
      number_format: 0.##
      auto_import: /utils.ftl as utils


shiro:
  web:
    enabled: true
  annotations:
    enabled: false
  loginUrl: /login
  successUrl: /index
  unauthorizedUrl: /error/reject.html
  sessionManager:
    cookie:
      maxAge: 604800
  rememberMeManager:
    cookie:
      maxAge: 604800
site:
  version: 3.5.0
  location: ${user.dir}
  controls:

    register: true

    register_email_validate: false

    post: true

    comment: true
  options:
    theme: classic
    site_logo: /dist/images/logo/logo.png
    site_favicon: /dist/images/logo/m.png
    storage_max_width: 800
    storage_limit_size: 2
    editor: markdown
    thumbnail_channel_size: 200x112
    thumbnail_post_size: 360x200
    storage_scheme: fastdfs
    site_copyright: Mengzyy
#    storage_scheme: native

#fastdfs配置
###################以下为fdfs增加的配置###########################
fdfs:
  reqHost: 122.112.150.62
  reqPort: 8888
  #分布式文件系统FastDFS配置
  #fdfs.pool.jmx-enabled=false
  thumb-image.width: 150
  thumb-image.height: 150
  connect-timeout: 600
  so-timeout: 1500
  trackerList: 122.112.150.62:22122
  thumbImage.height: 150
  thumbImage.width: 150
  #spring.jmx.enabled=false
  pool:
    max-total: 10
###################以上为fdfs增加的配置###########################
